api/urls.py
from django.urls import path
from api import views
from rest_framework import routers as rest_routers
from drf_spectacular.views import SpectacularJSONAPIView, SpectacularSwaggerView


app_name = "api"

router = rest_routers.SimpleRouter()
router.register("categories", views.CategoryViewSet)

urlpatterns = [
    path("products/", views.ProductListView.as_view(), name="api_product_list"),
    path(
        "products/<int:pk>/",
        views.ProductDetailView.as_view(),
        name="api_product_detail",
    ),
    path("swagger/", SpectacularJSONAPIView.as_view(), name="swagger"),
    path(
        "swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="api:swagger"),
        name="api_swagger_ui",
    ),
]

urlpatterns += router.urls

cart/urls.py
from django.urls import path

from cart import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

coupons/urls.py
from django.urls import path

from coupons import views


app_name = "coupons"


urlpatterns = [path("apply/", views.coupon_apply, name="apply")]

django_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path("cart/", include("cart.urls")),
    path("admin/", admin.site.urls),
    path("orders/", include("orders.urls")),
    path("payment/", include("payment.urls")),
    path("coupons/", include("coupons.urls")),
    path("rosetta/", include("rosetta.urls")),
    path("", include("shop.urls")),
)

urlpatterns += [
    path("api/v1/", include("api.urls", namespace="api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders import views


app_name = "orders"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
    path(
        "staff/order/<int:order_id>/pdf",
        views.staff_order_pdf,
        name="staff_order_pdf",
    ),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.forms import Form


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

cart/views.py
from django.http import HttpRequest
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404, redirect, render

from cart.cart import Cart
from cart.forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from recommendation.recommender import Recommender
from shop.models import Product

# Create your views here.


@require_POST
def cart_add(request: HttpRequest, product_id):
    cart = Cart(request=request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        cart.add(
            product=product,
            quantity=cleaned_data["quantity"],
            override=cleaned_data["override"],
        )
    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request: HttpRequest, product_id):
    cart = Cart(request=request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product=product)
    return redirect("cart:cart_detail")


def cart_detail(request: HttpRequest):
    cart = Cart(request=request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(
            initial={"quantity": item["quantity"], "override": True}
        )
    coupon_apply_form = CouponApplyForm()
    rc = Recommender()
    cart_products = [item["product"] for item in cart]
    if cart_products:
        recommended_products = rc.suggest_products_for(cart_products)
    else:
        recommended_products = []
    return render(
        request,
        "cart/detail.html",
        {
            "cart": cart,
            "coupon_apply_form": coupon_apply_form,
            "recommended_products": recommended_products,
        },
    )

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}
<p class="is-size-2 mt-4 mb-4">{% trans "Your shopping cart" %}</p>
<div class="grid is-gap-8">
    <div class="cell">
        <table class="cart table">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit price</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <figure class="image is-128x128">
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                            </figure>
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.override }}
                            <input type="submit" class="button is-outlined is-success mt-2" value="Update">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                            <input type="submit" class="button is-black" value="Remove">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
                {% endwith %}
                {% endfor %}
                {% if cart.coupon %}
                <tr class="subtotal">
                    <td>Subtotal</td>
                    <td colspan="4"></td>
                    <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
                </tr>
                <tr>
                    <td>
                        "{{ cart.coupon.code }}" coupon
                        ({{ cart.coupon.discount }}% off)
                    </td>
                    <td colspan="4"></td>
                    <td class="num neg">
                        - ${{ cart.get_discount|floatformat:2 }}
                    </td>
                </tr>
                {% endif %}
                <tr class="total">
                    <td class="has-text-weight-bold">Total</td>
                    <td colspan="4"></td>
                    <td class="num has-text-weight-bold">${{ cart.get_total_price_after_discount|floatformat:2 }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="cell">
        <p class="is-size-4">Apply a coupon:</p>
        <form action="{% url 'coupons:apply' %}" method="post">
            {{ coupon_apply_form }}
            <input type="submit" class="button is-black" value="Apply" style="margin-top: .5rem;">
            {% csrf_token %}
        </form>
        <p class="mt-5">
            <a href="{% url 'shop:product_list' %}" class="button
    light is-fullwidth">Continue shopping</a>
            <a href="{% url 'orders:order_create' %}" class="button mt-4 is-success is-fullwidth">Checkout</a>
        </p>
    </div>
</div>

{% if recommended_products %}
<p class="is-size-3 mt-4 mb-4">{% trans "People who bought this also bought" %}</p>
<div class="fixed-grid has-5-cols">
    <div class="grid">
        {% for p in recommended_products %}
        <div class="cell">
            <a href="{{ p.get_absolute_url }}">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-fullwidth">
                            <img src="{{ p.image.url }}" alt="Placeholder image" />
                        </figure>
                    </div>
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-5">{{ p.name }} </p>
                            </div>
                            <div class="media-right">
                                <p class="subtitle is-6">${{ p.price }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}