api/urls.py
from django.urls import path
from api import views
from rest_framework import routers as rest_routers
from drf_spectacular.views import SpectacularJSONAPIView, SpectacularSwaggerView


app_name = "api"

router = rest_routers.SimpleRouter()
router.register("categories", views.CategoryViewSet)

urlpatterns = [
    path("products/", views.ProductListView.as_view(), name="api_product_list"),
    path(
        "products/<int:pk>/",
        views.ProductDetailView.as_view(),
        name="api_product_detail",
    ),
    path("swagger/", SpectacularJSONAPIView.as_view(), name="swagger"),
    path(
        "swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="api:swagger"),
        name="api_swagger_ui",
    ),
]

urlpatterns += router.urls

django_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path("cart/", include("cart.urls")),
    path("admin/", admin.site.urls),
    path("orders/", include("orders.urls")),
    path("payment/", include("payment.urls")),
    path("coupons/", include("coupons.urls")),
    path("rosetta/", include("rosetta.urls")),
    path("", include("shop.urls")),
)

urlpatterns += [
    path("api/v1/", include("api.urls", namespace="api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path

from payment import views


app_name = "payment"

urlpatterns = [
    path("process/", views.payment_process, name="process"),
    path("completed/", views.payment_completed, name="completed"),
    path("canceled/", views.payment_canceled, name="canceled"),
    path("webhook/", views.stripe_webhook, name="webhook"),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from decimal import Decimal
from http import HTTPStatus
from pickle import FALSE
from uu import Error
from django.conf import settings
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from requests import session
import stripe
import logging
from .tasks import payment_completed as payment_completed_task

logger = logging.getLogger(__name__)


from orders.models import Order

stripe.api_key = settings.STRIPE_SECRET_KEY


# Create your views here.
def payment_process(request: HttpRequest):
    order_id = request.session.get("order_id", None)
    order = get_object_or_404(Order, id=order_id)
    if request.method == "POST":
        success_url = request.build_absolute_uri(reverse("payment:completed"))
        cancel_url = request.build_absolute_uri(reverse("payment:canceled"))
        line_items = []
        # TODO: deactivate order's coupon
        # if order.coupon != None:
        #     order.coupon.active = False
        #     order.coupon.save()
        for item in order.items.all():  # type: ignore
            line_items.append(
                {
                    "price_data": {
                        "unit_amount": int(
                            item.price * Decimal("100")
                        ),  # price * 100 cents
                        "currency": "usd",
                        "product_data": {"name": item.product.name},
                    },
                    "quantity": item.quantity,
                }
            )
        session_data = {
            "mode": "payment",
            "client_reference_id": order.id,  # type: ignore
            "success_url": success_url,
            "cancel_url": cancel_url,
            "line_items": line_items,
        }
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                name=order.coupon.code, percent_off=order.discount, duration="once"
            )
            session_data["discounts"] = [{"coupon": stripe_coupon.id}]
        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code=HTTPStatus.SEE_OTHER.value)  # type: ignore
    else:
        return render(
            request,
            "payment/process.html",
            {
                "order": order,
            },
        )


def payment_completed(request: HttpRequest):
    return render(request, "payment/completed.html")


def payment_canceled(request: HttpRequest):
    return render(request, "payment/canceled.html")


@csrf_exempt
@require_POST
def stripe_webhook(request: HttpRequest):
    event = None
    sig_header = request.META["HTTP_STRIPE_SIGNATURE"]
    try:
        event = stripe.Webhook.construct_event(
            request.body,
            sig_header,
            settings.STRIPE_WEBHOOK_SECRET,
        )
    except Error as evtErr:
        if settings.DEBUG:
            logger.warning("stripe_webhook error", evtErr)
        return HttpResponse(status=HTTPStatus.BAD_REQUEST.value)
    match event.type:
        case "checkout.session.completed":
            session = event.data.object
            if session["mode"] == "payment" and session["payment_status"] == "paid":
                order = get_object_or_404(Order, id=session["client_reference_id"])
                order.paid = True
                order.stripe_payment_intent = session["payment_intent"]
                order.save()
                payment_completed_task.delay(order.id)  # type: ignore
        case _:
            pass
    return HttpResponse(status=HTTPStatus.OK.value)

payment/templates/payment/canceled.html
{% extends "shop/base.html" %}
{% block title %}Payment Canceled{% endblock %}
{% block content %}
<h1>Your payment has not been processed</h1>
<p>There was a problem processing your payment.</p>
{% endblock %}

payment/templates/payment/completed.html
{% extends "shop/base.html" %}
{% block title %}Payment Successful{% endblock %}
{% block content %}
<h1>Your payment was successful</h1>
<p>Your payment has been processed successfully.</p>
{% endblock %}

payment/templates/payment/process.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Checkout{% endblock %}
{% block content %}
<h1>Order summary</h1>
<table class="cart">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% for item in order.items.all %}
        <tr class="row{% cycle '1' '2' %}">
            <td>
                <img src="{% if item.product.image %}{{ item.product.image.url }}
              {% else %}{% static 'img/no_image.png' %}{% endif %}">
            </td>
            <td>{{ item.product.name }}</td>
            <td class="num">${{ item.price }}</td>
            <td class="num">{{ item.quantity }}</td>
            <td class="num">${{ item.get_cost }}</td>
        </tr>
        {% endfor %}
        {% if order.coupon %}
        <tr class="subtotal">
            <td>Subtotal</td>
            <td colspan="3"></td>
            <td class="num">
                ${{ order.get_total_cost_before_discount|floatformat:2 }}
            </td>
        </tr>
        <tr>
            <td>
                "{{ order.coupon.code }}" coupon
                ({{ order.discount }}% off)
            </td>
            <td colspan="3"></td>
            <td class="num neg">
                - ${{ order.get_discount|floatformat:2 }}
            </td>
        </tr>
        {% endif %}
        <tr class="total">
            <td colspan="4">Total</td>
            <td class="num">${{ order.get_total_cost }}</td>
        </tr>
    </tbody>
</table>
<form action="{% url 'payment:process' %}" method="post">
    <input type="submit" value="Pay Now">
    {% csrf_token %}
</form>
{% endblock %}